name = "Newb Reimagined"
version = [0, 16, 1]
min_supported_mc_version = [1, 21, 130]
description = '''
§c%w
§7A fantasy-themed shader while preserving the vanilla Minecraft feel.
%v
''' # %w = patch warning, %v = version
authors = ["alvyrei", "devendrn"]
url = " "
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "CUSTOM2"
materials = ["Clouds"]
description = '''
Custom
§7

- Soft Clouds
- Aurora §bLight Blue §uPurple§7
- Blinking Torch
'''

[[subpack]]
define = "CUSTOM1"
materials = ["Clouds", "RenderChunk"]
description = '''
Custom
§7

- Double Layer Clouds
- Chunk Loading Animation
- Blinking Torch
'''

[[subpack]]
define = "UNBOUND"
materials = ["RenderChunk", "Clouds", "Sky"]
description = '''
§6Unbound Style§r
§7Visuals and cloud styles like Complementary Unbound in Java.

- Fantasy/Realistic Clouds
- Shooting Stars
- Wavy Water
'''

[[subpack]]
define = "LOW"
materials = ["RenderChunk"]
description = '''
§aLow§r
§7Disable most features to increase your fps.

- Disable Glow Leak
- Disable Fake Depth
- Disable Direct Light and more optimized!
'''

[[subpack]]
define = "MEDIUM"
materials = ["RenderChunk", "Clouds"]
description = '''
§eMedium§r
§7Perfect for perfomance without losing many fps.

- Aurora §bLight Blue §uPurple§7
- Reducing Plants Wave
- Disable Ground Reflection
'''

[[subpack]]
define = "HIGH"
materials = ["RenderChunk", "Sky"]
description = '''
§cHigh§r
§7Enable all the advanced features.

- Fake Depth
- Glow Leak
- Galaxy Stars and more!
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
§7Just the default experience!

- Reimagined/Rounded Clouds
- Disable Aurora & Fake Depth
- Optimized
'''